  
name: 'Terrapin-CI'

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@master
    - name: list output folder
      run:  mkdir $(pwd)/outputfolder
    - name: Build the Docker image
      run:  docker run --volume $(pwd):/repo --volume $(pwd)/outputfolder:/output 'mcr.microsoft.com/oryx/build:latest' /bin/bash -c "oryx build -package /repo --output /output"
    - name: list output folder
      run:  ls $(pwd)/outputfolder
    - uses: jikuma/githubaction@v0.3.3-alpha
      name: 'Create a release'
      with:
        operation: 'create a release'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release_title: 'Terrapin release'
        release_note: 'Terrapin release for commit ${{ github.sha }}'
        asset_filepath: $(pwd)/outputfolder/${{ PACKAGE_NAME }}-${{ PACKAGE_VERSION }}.tgz
        tag_name: v0.1.GITHUB_SHORT_SHA
      env:
        package_name: "http-proxy-agent"
        package_version: "2.1.0"
